sudo: required

services:
  - docker

before_install:
   # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

language: python
python:
  - "3.6"
install:
  - pip install -r ./requirements.txt
# command to run tests
script:
# unit test
  - python -m pytest -v --cov
  - coveralls      
  - docker build -f Dockerfile -t $DOCKER_USERNAME/7552-app-server .
  - docker tag $DOCKER_USERNAME/7552-app-server registry.heroku.com/$HEROKU_APP_NAME/web


deploy:
  provider: script
  script:
    # push to dockerhub
    docker push guidotrucco/7552-app-server;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  branch: master

