sudo: required

services:
  - docker

before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - sudo service postgresql stop

install:
  - pip install -r ./requirements.txt
  - docker build -f Dockerfile -t 7552-app-server .
  - docker-compose -f docker-compose.yml up

# command to run tests
script:
# unit test
  - python -m pytest -v
  - coveralls      
  - docker build -f Dockerfile -t $DOCKER_USERNAME/7552-app-server .

after_script:
  - docker-compose -f docker-compose.yml stop
  - docker-compose -f docker-compose.yml down

deploy:
  provider: script
  script:
    # push to dockerhub
    docker push guidotrucco/7552-app-server;
  branch: master

