sudo: required

services:
  - docker

before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

language: python
python:
  - "3.6"
install:
  - pip install -r ./requirements.txt
# command to run tests
script:
# unit test
  - python -m pytest -v 
  - coveralls      
  - docker build -f Dockerfile -t $DOCKER_USERNAME/7552-app-server .


deploy:
  provider: script
  script:
    # push to dockerhub
    docker push guidotrucco/7552-app-server;
  branch: master

