version: "3"
services:
  app-server:
    image: guidotrucco/7552-app-server
    #build: . #Para correr de forma local
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
