version: "3"
services:
  app-server:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file: .env
