version: "3.4"
services:
  app-server:
    build: #Para correr de forma local
      context: .
      dockerfile: Dockerfile.local
      target: code_files
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
