version: "3.4"
services:
  app-server:
    image: guidotrucco/7552-app-server
    env_file: .env
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
