version: "3"
services:
  app-server:
    image: "7552-app-server"
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
